set dotenv-load

calendar:
    aoc calendar --year 2023

read:
    aoc read --year 2023

submit day solution:
    aoc submit --year 2023 --day {{day}} {{solution}}

download day:
    #!/usr/bin/env bash
    set -euxo pipefail
    mkdir -p day{{day}}
    cd day{{day}}
    aoc download --overwrite --year 2023 --day {{day}}

test day:
    duckdb < {{day}}/test.sql

solve day:
    duckdb < {{day}}/{{day}}.sql
